apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant
  labels:
    app: qdrant
    component: database
data:
  initialize.sh: |
    #!/bin/sh
    SET_INDEX=${HOSTNAME##*-}
    echo "Starting initializing for pod $SET_INDEX"
    exec ./entrypoint.sh --uri "http://qdrant-$SET_INDEX.qdrant:6335"
  production.yaml: |
    storage:
      storage_path: /qdrant/storage
      snapshots_path: /qdrant/snapshots
      on_disk_payload: true
      
    service:
      http_port: 6333
      grpc_port: 6334
      enable_cors: true
      
    cluster:
      enabled: true
      p2p:
        port: 6335
      consensus:
        tick_period_ms: 100
