apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qdrant
  labels:
    app: qdrant
    component: database
spec:
  endpoints:
    - honorLabels: true
      interval: 30s
      path: /metrics
      port: http
      scheme: http
      scrapeTimeout: 10s
  selector:
    matchLabels:
      app: qdrant
      component: database
