import type { PaperBlock, PaperMetadata } from "#/components/latex/model/types";

/** Escape plain text for LaTeX body (minimal safe set). */
export function escapeLatexText(text: string): string {
	return text
		.replaceAll("\\", "\\textbackslash{}")
		.replaceAll("{", "\\{")
		.replaceAll("}", "\\}")
		.replaceAll("$", "\\$")
		.replaceAll("&", "\\&")
		.replaceAll("%", "\\%")
		.replaceAll("#", "\\#")
		.replaceAll("_", "\\_")
		.replaceAll("^", "\\textasciicircum{}")
		.replaceAll("~", "\\textasciitilde{}");
}

function headingCommand(level: 1 | 2 | 3): string {
	switch (level) {
		case 1:
			return "section";
		case 2:
			return "subsection";
		case 3:
			return "subsubsection";
		default: {
			const _n: never = level;
			return _n;
		}
	}
}

function blockToLatex(block: PaperBlock): string {
	if (block.type === "heading") {
		const escaped = escapeLatexText(block.text.trim());
		if (!escaped) {
			return `% empty ${headingCommand(block.level)}`;
		}
		return `\\${headingCommand(block.level)}{${escaped}}`;
	}
	if (block.type === "equation") {
		return block.display
			? `\\[\n${block.latex}\n\\]`
			: `$${block.latex}$`;
	}
	const lines = block.text
		.split("\n")
		.map((line) => escapeLatexText(line.trim()))
		.filter(Boolean);
	if (lines.length === 0) {
		return "";
	}
	return `${lines.join("\\\\\n")}\n\n`;
}

/** Build a \documentclass article with metadata and escaped body blocks. */
export function exportPaperToLatex(
	meta: PaperMetadata,
	blocks: PaperBlock[],
): string {
	const title = escapeLatexText(meta.title.trim());
	const authorsRaw = meta.authors.trim();
	const authors = escapeLatexText(authorsRaw.replaceAll("\n", ", "));
	const abstract = escapeLatexText(meta.abstract.trim());
	const keywords = escapeLatexText(meta.keywords.trim());

	const body = blocks.map(blockToLatex).filter(Boolean).join("\n");

	const lines: string[] = [
		"% Generated by Caramba — safe to compile on the server",
		"\\documentclass{article}",
		"\\usepackage[utf8]{inputenc}",
		"\\begin{document}",
		"",
	];

	if (title) {
		lines.push(`\\title{${title}}`, "");
	}
	if (authors) {
		lines.push(`\\author{${authors}}`, "");
	}
	if (title || authors) {
		lines.push("\\maketitle", "");
	}
	if (abstract) {
		lines.push("\\begin{abstract}", abstract, "\\end{abstract}", "");
	}
	if (keywords) {
		lines.push(`\\textbf{Keywords:} ${keywords}`, "");
	}
	lines.push(body, "\\end{document}", "");
	return lines.join("\n");
}
