// Code generated by hand for performance.
// SPDX-License-Identifier: Apache-2.0
//
// NEON vectorized log(x) for f32. Algorithm:
//   1. bits = float32bits(x)
//   2. e = ((bits >> 23) & 0xFF) - 127   ; binary exponent
//   3. M  = float32frombits((bits & 0x7FFFFF) | 0x3F800000)
//      → M ∈ [1, 2)
//   4. log(x) = e * ln2 + log(M)
//   5. log(M) via the substitution y = (M-1)/(M+1):
//         log(M) = 2 * (y + y³/3 + y⁵/5 + y⁷/7 + y⁹/9 + y¹¹/11)
//      Since |y| < 1/3, this is ~5 ULP accurate at f32.
//
// Real NEON per AGENTS.md §1.1.

#include "textflag.h"

#define VFADD_S4(m, n, d)   WORD $(0x4E20D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFSUB_S4(m, n, d)   WORD $(0x4EA0D400 | ((m) << 16) | ((n) << 5) | (d))
#define VFMUL_S4(m, n, d)   WORD $(0x6E20DC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFMLA_S4(m, n, d)   WORD $(0x4E20CC00 | ((m) << 16) | ((n) << 5) | (d))
#define VFDIV_S4(m, n, d)   WORD $(0x6E20FC00 | ((m) << 16) | ((n) << 5) | (d))
#define VUSHR_S4_BY23(n, d) WORD $(0x6F290400 | ((n) << 5) | (d))
#define VISUB_S4(m, n, d)   WORD $(0x6EA08400 | ((m) << 16) | ((n) << 5) | (d))
#define VAND_B16(m, n, d)   WORD $(0x4E201C00 | ((m) << 16) | ((n) << 5) | (d))
#define VORR_B16(m, n, d)   WORD $(0x4EA01C00 | ((m) << 16) | ((n) << 5) | (d))
#define VSCVTF_S4(n, d)     WORD $(0x4E21D800 | ((n) << 5) | (d))
#define VMOV_B16(src, dst)  WORD $(0x4EA01C00 | ((src) << 16) | ((src) << 5) | (dst))

DATA  logC<>+0(SB)/4, $0.6931471805599453   // ln2
DATA  logC<>+4(SB)/4, $1.0                  // 1.0
DATA  logC<>+8(SB)/4, $0.09090909           // 1/11
DATA  logC<>+12(SB)/4, $0.11111111          // 1/9
DATA  logC<>+16(SB)/4, $0.14285715          // 1/7
DATA  logC<>+20(SB)/4, $0.20000000          // 1/5
DATA  logC<>+24(SB)/4, $0.33333334          // 1/3
DATA  logC<>+28(SB)/4, $2.0                 // 2.0 (final scale)
GLOBL logC<>(SB), 8, $32

// Pre-built bitmasks. Loaded via integer reg then VMOV-broadcast.
//   exponentMask  = 0x7F800000   (used to extract exponent bits)
//   mantissaMask  = 0x007FFFFF
//   oneBits       = 0x3F800000   (bits of 1.0)
//   bias127       = 127 (int32)

// func LogFloat32NEONAsm(dst, src *float32, n int)
TEXT ·LogFloat32NEONAsm(SB), NOSPLIT, $0-24
    MOVD dst+0(FP), R0
    MOVD src+8(FP), R1
    MOVD n+16(FP), R2

    MOVD $logC<>(SB), R3
    FMOVS  0(R3), F16  ; VDUP V16.S[0], V16.S4   // ln2
    FMOVS  4(R3), F17  ; VDUP V17.S[0], V17.S4   // 1.0
    FMOVS  8(R3), F18  ; VDUP V18.S[0], V18.S4   // 1/11
    FMOVS 12(R3), F19  ; VDUP V19.S[0], V19.S4   // 1/9
    FMOVS 16(R3), F20  ; VDUP V20.S[0], V20.S4   // 1/7
    FMOVS 20(R3), F21  ; VDUP V21.S[0], V21.S4   // 1/5
    FMOVS 24(R3), F22  ; VDUP V22.S[0], V22.S4   // 1/3
    FMOVS 28(R3), F23  ; VDUP V23.S[0], V23.S4   // 2.0

    // V24 = mantissa mask 0x007FFFFF broadcast
    MOVD $0x007FFFFF, R6
    VMOV R6, V24.S[0]
    VDUP V24.S[0], V24.S4
    // V25 = oneBits 0x3F800000 broadcast
    MOVD $0x3F800000, R6
    VMOV R6, V25.S[0]
    VDUP V25.S[0], V25.S4
    // V26 = bias 127 (int32) broadcast
    MOVD $127, R6
    VMOV R6, V26.S[0]
    VDUP V26.S[0], V26.S4

log_loop4:
    CMP  $4, R2
    BLT  log_done
    VLD1.P 16(R1), [V0.S4]
    // V1 = (bits >> 23) - 127  → integer exponent
    VUSHR_S4_BY23(0, 1)
    VISUB_S4(26, 1, 1)
    // V2 = (bits & mantissaMask) | oneBits  → M as f32 bit pattern, M ∈ [1, 2)
    VAND_B16(24, 0, 2)
    VORR_B16(25, 2, 2)
    // Convert exponent to f32.
    VSCVTF_S4(1, 1)
    // y = (M - 1) / (M + 1)
    VFSUB_S4(17, 2, 3)            // V3 = M - 1
    VFADD_S4(17, 2, 4)            // V4 = M + 1
    VFDIV_S4(4, 3, 5)             // V5 = y
    // y² = V6
    VFMUL_S4(5, 5, 6)
    // Polynomial in y² using Horner: p(y²) = c0 + c1*y² + c2*y⁴ + c3*y⁶ + c4*y⁸ + c5*y¹⁰
    // where c_i = 1/(2i+1): c0=1, c1=1/3, c2=1/5, c3=1/7, c4=1/9, c5=1/11.
    // Then log(M) = 2 * y * p(y²).
    VMOV_B16(18, 7)               // p = 1/11
    VMOV_B16(19, 8) ; VFMLA_S4(6, 7, 8)   // p = 1/9 + y²·(1/11)
    VMOV_B16(20, 7) ; VFMLA_S4(6, 8, 7)   // p = 1/7 + y²·...
    VMOV_B16(21, 8) ; VFMLA_S4(6, 7, 8)   // p = 1/5 + y²·...
    VMOV_B16(22, 7) ; VFMLA_S4(6, 8, 7)   // p = 1/3 + y²·...
    VMOV_B16(17, 8) ; VFMLA_S4(6, 7, 8)   // p = 1   + y²·...
    // log(M) = 2 * y * p = V23 * V5 * V8
    VFMUL_S4(5, 8, 8)             // V8 = y * p
    VFMUL_S4(23, 8, 8)            // V8 = 2 * y * p = log(M)
    // result = e * ln2 + log(M)
    VFMLA_S4(16, 1, 8)            // V8 += V16 * V1 → V8 = log(M) + e*ln2
    VST1.P [V8.S4], 16(R0)
    SUB  $4, R2
    B    log_loop4

log_done:
    RET
