providers:
  openai: true
  anthropic: false
  gemini: false
  cohere: false
  deepseek: false
  huggingface: false
  nvidia: false
  ollama: false
  lmstudio: false

endpoints:
  openai: https://api.openai.com/v1
  anthropic: https://api.anthropic.com/v1
  gemini: https://generativelanguage.googleapis.com/v1beta/openai
  cohere: https://api.cohere.ai/v1
  deepseek: https://api.deepseek.com/v1
  huggingface: https://api-inference.huggingface.co/models
  nvidia: https://integrate.api.nvidia.com/v1
  ollama: http://localhost:11434
  lmstudio: http://localhost:8000

models:
  openai: gpt-4o-mini
  anthropic: claude-3-5-sonnet-latest
  gemini: gemini-1.5-flash
  cohere: command-r
  deepseek: deepseek-chat
  huggingface: gpt2
  nvidia: nvidia/llama-3.1-nemotron-70b-instruct
  ollama: deepseek-r1:8b
  lmstudio: bartowski/Llama-3.1-8B-Lexi-Uncensored-V2-GGUF

settings:
  domain: "caramba.ai"
  sentry:
    enabled: true
    dsn: "https://sentry.io/api/1234567890/store/"
    environment: "production"
    release: "1.0.0"
    sample_rate: 1.0
  defaults:
    provider: openai
    temperature: 0.7
    top_p: 1.0
    top_k: 40
    presence_penalty: 0.0
    frequency_penalty: 0.0
    max_tokens: 1024
    stop_sequences: []
    stream: true
    platform:
      os: linux
      arch: arm64
      variant: v8
  s3:
    bucket: "caramba"
  global:
    iteration_limit: 10

agents:
  ui:
    url: "https://alliedmastercomputer.org/.well-known/agents/default"
    name: "Caramba User Interface Agent"
    description: "An agent that interacts with a user."
    version: "1.0.0"
    provider:
      organization: "TheApeMachine"
      url: "https://github.com/theapemachine/caramba"
    authentication:
      schemes: "none"
    defaultInputModes:
      - "text/plain"
    defaultOutputModes:
      - "text/plain"
    capabilities:
      streaming: true
      pushNotifications: true
    skills:
      - id: "themapemachine/skill/delegation"
        name: "Delegation"
        description: "A skill that delegates tasks to other agents."
        tags:
          - "delegation"
          - "task"
        examples:
          - "Please research the current state-of-the-art in AI agent technology."
          - "I want to develop a new AI agent that can help me with my business."
          - "I need to find a new job."
        inputModes:
          - "text/plain"
        outputModes:
          - "text/plain"
