version: 2
name: dba_checkpoint_benchmark_sem8_geo32_v40
artifacts_dir: research/dba
notes: >
  Checkpoint benchmark for the sem=8/head, geo=32/head, v=40/head DBA scenario.
  Baseline is standard attention; student is DBA decoupled with sem=256, geo=1024, attn_dim=1280.

defaults:
  data:
    tokenizer: tiktoken:gpt2
    val_frac: 0.0
  logging:
    instrument: rich
    wandb: false
    wandb_project: ''
    wandb_entity: ''
    wandb_mode: disabled
    eval_iters: 0
  runtime:
    # Schema requires positive; checkpoint_compare does no training anyway.
    save_every: 1

vars:
  # --- Checkpoints (drop into research/dba/) ---
  baseline_ckpt: research/dba/ckpt_baseline_sem8geo32v40.pt
  decoupled_ckpt: research/dba/ckpt_decoupled_sem8geo32v40.pt

  # --- Dataset shard for perplexity ---
  dataset_path: fineweb_100m.npy
  block_size: 2048

  # --- Model dims (same as paper rerun preset) ---
  d_model: 2048
  n_layers: 22
  n_heads: 32
  d_ff: 5632
  vocab_size: 50304
  rope_base: 10000.0

  # --- DBA dims (per-head sem=8, geo=32, v=40) ---
  sem_dim: 256
  geo_dim: 1024
  attn_dim: 1280
  # Clarifies notes: value dim per head is derived from attn_dim / n_heads (=40 here).
  v_head_dim: 40

  # --- Runtime ---
  device: mps
  dtype: float32

targets:
  - type: experiment
    name: baseline_vs_decoupled_sem8geo32v40
    description: "Compare baseline vs DBA decoupled (sem8/geo32/v40) checkpoints."
    backend: torch
    task: task.language_modeling
    data:
      ref: dataset.tokens
      config:
        path: ${dataset_path}
        block_size: ${block_size}
    system:
      # Student model (DBA decoupled)
      ref: system.language_model
      config:
        model:
          type: TransformerModel
          tied_embeddings: false
          embedder:
            type: token
            vocab_size: ${vocab_size}
            d_model: ${d_model}
          topology:
            type: StackedTopology
            layers:
              - type: NestedTopology
                repeat: ${n_layers}
                layers:
                  - type: ResidualTopology
                    layers:
                      - type: RMSNormLayer
                        d_model: ${d_model}
                        eps: 1e-5
                      - type: AttentionLayer
                        d_model: ${d_model}
                        n_heads: ${n_heads}
                        mode: decoupled
                        dba_train_backend: sdpa
                        attn_dim: ${attn_dim}
                        sem_dim: ${sem_dim}
                        geo_dim: ${geo_dim}
                        rope_enabled: true
                        rope_base: ${rope_base}
                        rope_semantic: false
                        tie_qk: false
                        null_attn: false
                        decoupled_gate: false
                        is_causal: true
                        dropout_p: 0.0
                  - type: ResidualTopology
                    layers:
                      - type: RMSNormLayer
                        d_model: ${d_model}
                        eps: 1e-5
                      - type: SwiGLULayer
                        d_model: ${d_model}
                        d_ff: ${d_ff}
                        bias: false
              - type: RMSNormLayer
                d_model: ${d_model}
                eps: 1e-5
              - type: LinearLayer
                d_in: ${d_model}
                d_out: ${vocab_size}
                bias: false
    objective: objective.next_token_ce
    trainer:
      ref: trainer.checkpoint_compare
      config:
        teacher_ckpt: ${baseline_ckpt}
        student_ckpt: ${decoupled_ckpt}
        device: ${device}
        dtype: ${dtype}
        strict: true
        unsafe_pickle_load: false
        teacher_model:
          type: TransformerModel
          tied_embeddings: false
          embedder:
            type: token
            vocab_size: ${vocab_size}
            d_model: ${d_model}
          topology:
            type: StackedTopology
            layers:
              - type: NestedTopology
                repeat: ${n_layers}
                layers:
                  - type: ResidualTopology
                    layers:
                      - type: RMSNormLayer
                        d_model: ${d_model}
                        eps: 1e-5
                      - type: AttentionLayer
                        d_model: ${d_model}
                        n_heads: ${n_heads}
                        mode: standard
                        rope_enabled: true
                        rope_base: ${rope_base}
                        is_causal: true
                        dropout_p: 0.0
                  - type: ResidualTopology
                    layers:
                      - type: RMSNormLayer
                        d_model: ${d_model}
                        eps: 1e-5
                      - type: SwiGLULayer
                        d_model: ${d_model}
                        d_ff: ${d_ff}
                        bias: false
              - type: RMSNormLayer
                d_model: ${d_model}
                eps: 1e-5
              - type: LinearLayer
                d_in: ${d_model}
                d_out: ${vocab_size}
                bias: false
    runs:
      - id: eval
        mode: train
        exp: benchmark_only
        seed: 1337
        steps: 1
        expected: {phase: standard}
        train:
          phase: standard
          batch_size: 1
          block_size: ${block_size}
          # Schema requires positive; this run is a no-op for checkpoint_compare.
          lr: 1.0e-9
          device: ${device}
          dtype: ${dtype}
    benchmarks:
      - id: ppl_fineweb_100m
        config:
          type: perplexity
          dataset: ${dataset_path}
          block_size: ${block_size}
          batch_size: 1
          num_batches: 50
        models: [teacher, student]

      - id: ppl_fineweb_100m_deeper
        config:
          type: perplexity
          dataset: ${dataset_path}
          block_size: ${block_size}
          batch_size: 1
          num_batches: 200
        models: [teacher, student]

      - id: latency_cached
        config:
          type: latency
          prompt_lengths: [128, 512, 1024, 2048]
          generation_lengths: [128]
          batch_sizes: [1]
          warmup_runs: 2
          timed_runs: 5
          use_cache: true
          cache_kind: fp16
        models: [teacher, student]

      - id: latency_cached_long_prompt
        config:
          type: latency
          prompt_lengths: [2048, 4096, 8192]
          generation_lengths: [64]
          batch_sizes: [1]
          warmup_runs: 1
          timed_runs: 3
          use_cache: true
          cache_kind: fp16
        models: [teacher, student]

      - id: memory_kv
        config:
          type: memory
          sequence_lengths: [512, 1024, 2048, 4096]
          batch_sizes: [1]
          measure_peak: true
          measure_kvcache: true
          quantization_modes: [fp16]
        models: [teacher, student]

      - id: memory_kv_long
        config:
          type: memory
          sequence_lengths: [2048, 4096, 8192, 16384]
          batch_sizes: [1]
          measure_peak: true
          measure_kvcache: true
          quantization_modes: [fp16]
        models: [teacher, student]

      - id: behavior_sanity
        config:
          type: behavior
          tokenizer:
            type: tiktoken
            encoding: gpt2
          cases_file: research/dba/behavior_cases.yml
          max_new_tokens: 32
          context_window: 2048
        models: [teacher, student]

      - id: context_sweep
        config:
          type: context
          dataset: ${dataset_path}
          # NOTE: this preset defaults to device=mps; avoid very large contexts that would
          # materialize huge causal masks / KV caches and OOM. If running on CUDA, you can
          # extend this list and increase max_mask_elems accordingly (≈ L^2 for full masks).
          context_lengths: [2048, 4096, 8192]
          chunk_size: 512
          # Must be >= max(context_lengths)^2 when a full attention mask is built.
          max_mask_elems: 80000000
          batch_size: 1
          decode_len: 128
          decode_warmup: 8
          cache_kind: fp16
        models: [teacher, student]

entrypoints:
  default: "target:baseline_vs_decoupled_sem8geo32v40"

