apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radix
spec:
  serviceName: radix-headless
  replicas: 3
  selector:
    matchLabels:
      app: radix
  template:
    metadata:
      labels:
        app: radix
    spec:
      containers:
        - name: radix
          image: your-radix-image
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          ports:
            - containerPort: 6380
              name: peer
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: radix-headless
spec:
  clusterIP: None
  selector:
    app: radix
  ports:
    - port: 6380
      name: peer
