/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResearchIndexRouteImport } from './routes/research/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ResearchPaperRouteImport } from './routes/research/paper'
import { Route as ResearchNewRouteImport } from './routes/research/new'
import { Route as PaperEditRouteImport } from './routes/paper/edit'
import { Route as ApiAssistantRouteImport } from './routes/api/assistant'
import { Route as ResearchEditRouteRouteImport } from './routes/research/edit/route'
import { Route as ResearchEditIndexRouteImport } from './routes/research/edit/index'
import { Route as ResearchEditResearchPaperRouteImport } from './routes/research/edit/research-paper'
import { Route as ResearchEditModelScopeRouteImport } from './routes/research/edit/model-scope'
import { Route as ApiComputeOptimizerRouteImport } from './routes/api/compute/optimizer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPaperRoute = ResearchPaperRouteImport.update({
  id: '/research/paper',
  path: '/research/paper',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchNewRoute = ResearchNewRouteImport.update({
  id: '/research/new',
  path: '/research/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperEditRoute = PaperEditRouteImport.update({
  id: '/paper/edit',
  path: '/paper/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantRoute = ApiAssistantRouteImport.update({
  id: '/api/assistant',
  path: '/api/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchEditRouteRoute = ResearchEditRouteRouteImport.update({
  id: '/research/edit',
  path: '/research/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchEditIndexRoute = ResearchEditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ResearchEditRouteRoute,
} as any)
const ResearchEditResearchPaperRoute =
  ResearchEditResearchPaperRouteImport.update({
    id: '/research-paper',
    path: '/research-paper',
    getParentRoute: () => ResearchEditRouteRoute,
  } as any)
const ResearchEditModelScopeRoute = ResearchEditModelScopeRouteImport.update({
  id: '/model-scope',
  path: '/model-scope',
  getParentRoute: () => ResearchEditRouteRoute,
} as any)
const ApiComputeOptimizerRoute = ApiComputeOptimizerRouteImport.update({
  id: '/api/compute/optimizer',
  path: '/api/compute/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/research/edit': typeof ResearchEditRouteRouteWithChildren
  '/api/assistant': typeof ApiAssistantRoute
  '/paper/edit': typeof PaperEditRoute
  '/research/new': typeof ResearchNewRoute
  '/research/paper': typeof ResearchPaperRoute
  '/docs/': typeof DocsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/api/compute/optimizer': typeof ApiComputeOptimizerRoute
  '/research/edit/model-scope': typeof ResearchEditModelScopeRoute
  '/research/edit/research-paper': typeof ResearchEditResearchPaperRoute
  '/research/edit/': typeof ResearchEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/assistant': typeof ApiAssistantRoute
  '/paper/edit': typeof PaperEditRoute
  '/research/new': typeof ResearchNewRoute
  '/research/paper': typeof ResearchPaperRoute
  '/docs': typeof DocsIndexRoute
  '/research': typeof ResearchIndexRoute
  '/api/compute/optimizer': typeof ApiComputeOptimizerRoute
  '/research/edit/model-scope': typeof ResearchEditModelScopeRoute
  '/research/edit/research-paper': typeof ResearchEditResearchPaperRoute
  '/research/edit': typeof ResearchEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/research/edit': typeof ResearchEditRouteRouteWithChildren
  '/api/assistant': typeof ApiAssistantRoute
  '/paper/edit': typeof PaperEditRoute
  '/research/new': typeof ResearchNewRoute
  '/research/paper': typeof ResearchPaperRoute
  '/docs/': typeof DocsIndexRoute
  '/research/': typeof ResearchIndexRoute
  '/api/compute/optimizer': typeof ApiComputeOptimizerRoute
  '/research/edit/model-scope': typeof ResearchEditModelScopeRoute
  '/research/edit/research-paper': typeof ResearchEditResearchPaperRoute
  '/research/edit/': typeof ResearchEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/research/edit'
    | '/api/assistant'
    | '/paper/edit'
    | '/research/new'
    | '/research/paper'
    | '/docs/'
    | '/research/'
    | '/api/compute/optimizer'
    | '/research/edit/model-scope'
    | '/research/edit/research-paper'
    | '/research/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/assistant'
    | '/paper/edit'
    | '/research/new'
    | '/research/paper'
    | '/docs'
    | '/research'
    | '/api/compute/optimizer'
    | '/research/edit/model-scope'
    | '/research/edit/research-paper'
    | '/research/edit'
  id:
    | '__root__'
    | '/'
    | '/research/edit'
    | '/api/assistant'
    | '/paper/edit'
    | '/research/new'
    | '/research/paper'
    | '/docs/'
    | '/research/'
    | '/api/compute/optimizer'
    | '/research/edit/model-scope'
    | '/research/edit/research-paper'
    | '/research/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResearchEditRouteRoute: typeof ResearchEditRouteRouteWithChildren
  ApiAssistantRoute: typeof ApiAssistantRoute
  PaperEditRoute: typeof PaperEditRoute
  ResearchNewRoute: typeof ResearchNewRoute
  ResearchPaperRoute: typeof ResearchPaperRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  ApiComputeOptimizerRoute: typeof ApiComputeOptimizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/paper': {
      id: '/research/paper'
      path: '/research/paper'
      fullPath: '/research/paper'
      preLoaderRoute: typeof ResearchPaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/new': {
      id: '/research/new'
      path: '/research/new'
      fullPath: '/research/new'
      preLoaderRoute: typeof ResearchNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paper/edit': {
      id: '/paper/edit'
      path: '/paper/edit'
      fullPath: '/paper/edit'
      preLoaderRoute: typeof PaperEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant': {
      id: '/api/assistant'
      path: '/api/assistant'
      fullPath: '/api/assistant'
      preLoaderRoute: typeof ApiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/edit': {
      id: '/research/edit'
      path: '/research/edit'
      fullPath: '/research/edit'
      preLoaderRoute: typeof ResearchEditRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/edit/': {
      id: '/research/edit/'
      path: '/'
      fullPath: '/research/edit/'
      preLoaderRoute: typeof ResearchEditIndexRouteImport
      parentRoute: typeof ResearchEditRouteRoute
    }
    '/research/edit/research-paper': {
      id: '/research/edit/research-paper'
      path: '/research-paper'
      fullPath: '/research/edit/research-paper'
      preLoaderRoute: typeof ResearchEditResearchPaperRouteImport
      parentRoute: typeof ResearchEditRouteRoute
    }
    '/research/edit/model-scope': {
      id: '/research/edit/model-scope'
      path: '/model-scope'
      fullPath: '/research/edit/model-scope'
      preLoaderRoute: typeof ResearchEditModelScopeRouteImport
      parentRoute: typeof ResearchEditRouteRoute
    }
    '/api/compute/optimizer': {
      id: '/api/compute/optimizer'
      path: '/api/compute/optimizer'
      fullPath: '/api/compute/optimizer'
      preLoaderRoute: typeof ApiComputeOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResearchEditRouteRouteChildren {
  ResearchEditModelScopeRoute: typeof ResearchEditModelScopeRoute
  ResearchEditResearchPaperRoute: typeof ResearchEditResearchPaperRoute
  ResearchEditIndexRoute: typeof ResearchEditIndexRoute
}

const ResearchEditRouteRouteChildren: ResearchEditRouteRouteChildren = {
  ResearchEditModelScopeRoute: ResearchEditModelScopeRoute,
  ResearchEditResearchPaperRoute: ResearchEditResearchPaperRoute,
  ResearchEditIndexRoute: ResearchEditIndexRoute,
}

const ResearchEditRouteRouteWithChildren =
  ResearchEditRouteRoute._addFileChildren(ResearchEditRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResearchEditRouteRoute: ResearchEditRouteRouteWithChildren,
  ApiAssistantRoute: ApiAssistantRoute,
  PaperEditRoute: PaperEditRoute,
  ResearchNewRoute: ResearchNewRoute,
  ResearchPaperRoute: ResearchPaperRoute,
  DocsIndexRoute: DocsIndexRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  ApiComputeOptimizerRoute: ApiComputeOptimizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
