apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: default
  labels:
    app: neo4j
type: Opaque
data:
  # Default password is 'neo4j'. You should change this in production.
  NEO4J_AUTH: "bmVvNGovbmVvNGo=" # neo4j/neo4j in base64
