apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-k8s-config
  namespace: default
  labels:
    app: neo4j
data:
  server.default_listen_address: "0.0.0.0"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-user-config
  namespace: default
  labels:
    app: neo4j
data:
  # Neo4j user configuration settings
  dbms.security.auth_enabled: "true"
  server.http.enabled: "true"
  server.https.enabled: "false"
  server.metrics.jmx.enabled: "false"
  server.metrics.graphite.enabled: "false"
  server.metrics.prometheus.enabled: "false"
  server.backup.enabled: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-default-config
  namespace: default
  labels:
    app: neo4j
data:
  # Default Neo4j configuration
  dbms.memory.heap.initial_size: "1G"
  dbms.memory.heap.max_size: "1G"
  dbms.memory.pagecache.size: "512M"
