apiVersion: batch/v1
kind: Job
metadata:
  name: neo4j-cleanup
  namespace: default
  labels:
    app: neo4j
    helm.neo4j.com/pod_category: cleanup
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-weight": "3"
spec:
  template:
    metadata:
      labels:
        app: neo4j
        helm.neo4j.com/pod_category: cleanup
    spec:
      serviceAccountName: neo4j-cleanup
      containers:
        - name: kubectl
          image: bitnami/kubectl:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args:
            - -c
            - >-
              kubectl delete service -n default neo4j-lb-neo4j --ignore-not-found=true &&
              kubectl wait --for=delete service -n default neo4j-lb-neo4j
      restartPolicy: Never
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo4j-cleanup
  namespace: default
  labels:
    app: neo4j
    helm.neo4j.com/pod_category: cleanup
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neo4j-cleanup
  namespace: default
  labels:
    app: neo4j
    helm.neo4j.com/pod_category: cleanup
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neo4j-cleanup
  namespace: default
  labels:
    app: neo4j
    helm.neo4j.com/pod_category: cleanup
subjects:
  - kind: ServiceAccount
    name: neo4j-cleanup
roleRef:
  kind: Role
  name: neo4j-cleanup
  apiGroup: rbac.authorization.k8s.io
