apiVersion: v1
kind: Secret
metadata:
  name: neo4j-auth
  namespace: default
  labels:
    app: neo4j
type: Opaque
stringData:
  NEO4J_AUTH: "neo4j/neo4j" # Default credentials, should be changed in production
