apiVersion: v1
kind: ServiceAccount
metadata:
  name: neo4j
  namespace: default
  labels:
    app: neo4j
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: neo4j-service-reader
  namespace: default
  labels:
    app: neo4j
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services", "endpoints"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: neo4j-service-binding
  namespace: default
  labels:
    app: neo4j
subjects:
  - kind: ServiceAccount
    name: neo4j
roleRef:
  kind: Role
  name: neo4j-service-reader
  apiGroup: rbac.authorization.k8s.io
