apiVersion: v1
kind: Service
metadata:
  name: neo4j
  namespace: default
  labels:
    app: neo4j
    service: default
spec:
  type: ClusterIP
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-admin
  namespace: default
  labels:
    app: neo4j
    service: admin
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 6362
      targetPort: 6362
      name: tcp-backup
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-internals
  namespace: default
  labels:
    app: neo4j
    service: internals
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: neo4j
  ports:
    - protocol: TCP
      port: 6362
      targetPort: 6362
      name: tcp-backup
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: tcp-bolt
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: tcp-http
    - protocol: TCP
      port: 7688
      targetPort: 7688
      name: tcp-boltrouting
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: tcp-discovery
    - protocol: TCP
      port: 7000
      targetPort: 7000
      name: tcp-raft
    - protocol: TCP
      port: 6000
      targetPort: 6000
      name: tcp-tx
