// Code generated by capnpc-go. DO NOT EDIT.

package schema

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	fc "capnproto.org/go/capnp/v3/flowcontrol"
	schemas "capnproto.org/go/capnp/v3/schemas"
	server "capnproto.org/go/capnp/v3/server"
	stream "capnproto.org/go/capnp/v3/std/capnp/stream"
	context "context"
)

type ComputeProfile capnp.Struct

// ComputeProfile_TypeID is the unique identifier for the type ComputeProfile.
const ComputeProfile_TypeID = 0xb41f59a9a863bba3

func NewComputeProfile(s *capnp.Segment) (ComputeProfile, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return ComputeProfile(st), err
}

func NewRootComputeProfile(s *capnp.Segment) (ComputeProfile, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1})
	return ComputeProfile(st), err
}

func ReadRootComputeProfile(msg *capnp.Message) (ComputeProfile, error) {
	root, err := msg.Root()
	return ComputeProfile(root.Struct()), err
}

func (s ComputeProfile) String() string {
	str, _ := text.Marshal(0xb41f59a9a863bba3, capnp.Struct(s))
	return str
}

func (s ComputeProfile) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ComputeProfile) DecodeFromPtr(p capnp.Ptr) ComputeProfile {
	return ComputeProfile(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ComputeProfile) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ComputeProfile) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComputeProfile) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComputeProfile) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ComputeProfile) AvailableRunners() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s ComputeProfile) HasAvailableRunners() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ComputeProfile) SetAvailableRunners(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewAvailableRunners sets the availableRunners field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s ComputeProfile) NewAvailableRunners(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ComputeProfile) VramBytes() uint64 {
	return capnp.Struct(s).Uint64(0)
}

func (s ComputeProfile) SetVramBytes(v uint64) {
	capnp.Struct(s).SetUint64(0, v)
}

func (s ComputeProfile) RamBytes() uint64 {
	return capnp.Struct(s).Uint64(8)
}

func (s ComputeProfile) SetRamBytes(v uint64) {
	capnp.Struct(s).SetUint64(8, v)
}

func (s ComputeProfile) FlopPerSec() uint64 {
	return capnp.Struct(s).Uint64(16)
}

func (s ComputeProfile) SetFlopPerSec(v uint64) {
	capnp.Struct(s).SetUint64(16, v)
}

// ComputeProfile_List is a list of ComputeProfile.
type ComputeProfile_List = capnp.StructList[ComputeProfile]

// NewComputeProfile creates a new list of ComputeProfile.
func NewComputeProfile_List(s *capnp.Segment, sz int32) (ComputeProfile_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 1}, sz)
	return capnp.StructList[ComputeProfile](l), err
}

// ComputeProfile_Future is a wrapper for a ComputeProfile promised by a client call.
type ComputeProfile_Future struct{ *capnp.Future }

func (f ComputeProfile_Future) Struct() (ComputeProfile, error) {
	p, err := f.Future.Ptr()
	return ComputeProfile(p.Struct()), err
}

type NodeInfo capnp.Struct

// NodeInfo_TypeID is the unique identifier for the type NodeInfo.
const NodeInfo_TypeID = 0xef1cfd687cc33a62

func NewNodeInfo(s *capnp.Segment) (NodeInfo, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NodeInfo(st), err
}

func NewRootNodeInfo(s *capnp.Segment) (NodeInfo, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NodeInfo(st), err
}

func ReadRootNodeInfo(msg *capnp.Message) (NodeInfo, error) {
	root, err := msg.Root()
	return NodeInfo(root.Struct()), err
}

func (s NodeInfo) String() string {
	str, _ := text.Marshal(0xef1cfd687cc33a62, capnp.Struct(s))
	return str
}

func (s NodeInfo) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NodeInfo) DecodeFromPtr(p capnp.Ptr) NodeInfo {
	return NodeInfo(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NodeInfo) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NodeInfo) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NodeInfo) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NodeInfo) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NodeInfo) Id() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s NodeInfo) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NodeInfo) SetId(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s NodeInfo) Address() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s NodeInfo) HasAddress() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s NodeInfo) AddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s NodeInfo) SetAddress(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s NodeInfo) Profile() (ComputeProfile, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return ComputeProfile(p.Struct()), err
}

func (s NodeInfo) HasProfile() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s NodeInfo) SetProfile(v ComputeProfile) error {
	return capnp.Struct(s).SetPtr(2, capnp.Struct(v).ToPtr())
}

// NewProfile sets the profile field to a newly
// allocated ComputeProfile struct, preferring placement in s's segment.
func (s NodeInfo) NewProfile() (ComputeProfile, error) {
	ss, err := NewComputeProfile(capnp.Struct(s).Segment())
	if err != nil {
		return ComputeProfile{}, err
	}
	err = capnp.Struct(s).SetPtr(2, capnp.Struct(ss).ToPtr())
	return ss, err
}

// NodeInfo_List is a list of NodeInfo.
type NodeInfo_List = capnp.StructList[NodeInfo]

// NewNodeInfo creates a new list of NodeInfo.
func NewNodeInfo_List(s *capnp.Segment, sz int32) (NodeInfo_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[NodeInfo](l), err
}

// NodeInfo_Future is a wrapper for a NodeInfo promised by a client call.
type NodeInfo_Future struct{ *capnp.Future }

func (f NodeInfo_Future) Struct() (NodeInfo, error) {
	p, err := f.Future.Ptr()
	return NodeInfo(p.Struct()), err
}
func (p NodeInfo_Future) Profile() ComputeProfile_Future {
	return ComputeProfile_Future{Future: p.Future.Field(2, nil)}
}

type Tensor capnp.Struct

// Tensor_TypeID is the unique identifier for the type Tensor.
const Tensor_TypeID = 0xa83abc56c8f26634

func NewTensor(s *capnp.Segment) (Tensor, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return Tensor(st), err
}

func NewRootTensor(s *capnp.Segment) (Tensor, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return Tensor(st), err
}

func ReadRootTensor(msg *capnp.Message) (Tensor, error) {
	root, err := msg.Root()
	return Tensor(root.Struct()), err
}

func (s Tensor) String() string {
	str, _ := text.Marshal(0xa83abc56c8f26634, capnp.Struct(s))
	return str
}

func (s Tensor) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Tensor) DecodeFromPtr(p capnp.Ptr) Tensor {
	return Tensor(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Tensor) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Tensor) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Tensor) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Tensor) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Tensor) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Tensor) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Tensor) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Tensor) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Tensor) Shape() (capnp.Int64List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.Int64List(p.List()), err
}

func (s Tensor) HasShape() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Tensor) SetShape(v capnp.Int64List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewShape sets the shape field to a newly
// allocated capnp.Int64List, preferring placement in s's segment.
func (s Tensor) NewShape(n int32) (capnp.Int64List, error) {
	l, err := capnp.NewInt64List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.Int64List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s Tensor) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return []byte(p.Data()), err
}

func (s Tensor) HasData() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Tensor) SetData(v []byte) error {
	return capnp.Struct(s).SetData(2, v)
}

func (s Tensor) Dtype() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Tensor) HasDtype() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Tensor) DtypeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Tensor) SetDtype(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

// Tensor_List is a list of Tensor.
type Tensor_List = capnp.StructList[Tensor]

// NewTensor creates a new list of Tensor.
func NewTensor_List(s *capnp.Segment, sz int32) (Tensor_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[Tensor](l), err
}

// Tensor_Future is a wrapper for a Tensor promised by a client call.
type Tensor_Future struct{ *capnp.Future }

func (f Tensor_Future) Struct() (Tensor, error) {
	p, err := f.Future.Ptr()
	return Tensor(p.Struct()), err
}

type IRNode capnp.Struct

// IRNode_TypeID is the unique identifier for the type IRNode.
const IRNode_TypeID = 0x939aedf7ff71583b

func NewIRNode(s *capnp.Segment) (IRNode, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return IRNode(st), err
}

func NewRootIRNode(s *capnp.Segment) (IRNode, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return IRNode(st), err
}

func ReadRootIRNode(msg *capnp.Message) (IRNode, error) {
	root, err := msg.Root()
	return IRNode(root.Struct()), err
}

func (s IRNode) String() string {
	str, _ := text.Marshal(0x939aedf7ff71583b, capnp.Struct(s))
	return str
}

func (s IRNode) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (IRNode) DecodeFromPtr(p capnp.Ptr) IRNode {
	return IRNode(capnp.Struct{}.DecodeFromPtr(p))
}

func (s IRNode) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s IRNode) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s IRNode) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s IRNode) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s IRNode) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s IRNode) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s IRNode) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s IRNode) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s IRNode) Op() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s IRNode) HasOp() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s IRNode) OpBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s IRNode) SetOp(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s IRNode) Inputs() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return capnp.TextList(p.List()), err
}

func (s IRNode) HasInputs() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s IRNode) SetInputs(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewInputs sets the inputs field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s IRNode) NewInputs(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}
func (s IRNode) Config() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s IRNode) HasConfig() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s IRNode) SetConfig(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

// IRNode_List is a list of IRNode.
type IRNode_List = capnp.StructList[IRNode]

// NewIRNode creates a new list of IRNode.
func NewIRNode_List(s *capnp.Segment, sz int32) (IRNode_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[IRNode](l), err
}

// IRNode_Future is a wrapper for a IRNode promised by a client call.
type IRNode_Future struct{ *capnp.Future }

func (f IRNode_Future) Struct() (IRNode, error) {
	p, err := f.Future.Ptr()
	return IRNode(p.Struct()), err
}

type ComputeStream capnp.Client

// ComputeStream_TypeID is the unique identifier for the type ComputeStream.
const ComputeStream_TypeID = 0xa891bd6fb18acabb

func (c ComputeStream) WriteNode(ctx context.Context, params func(ComputeStream_writeNode_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa891bd6fb18acabb,
			MethodID:      0,
			InterfaceName: "pkg/network/schema/caramba.capnp:ComputeStream",
			MethodName:    "writeNode",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ComputeStream_writeNode_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c ComputeStream) WriteTensor(ctx context.Context, params func(ComputeStream_writeTensor_Params) error) error {
	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa891bd6fb18acabb,
			MethodID:      1,
			InterfaceName: "pkg/network/schema/caramba.capnp:ComputeStream",
			MethodName:    "writeTensor",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ComputeStream_writeTensor_Params(s)) }
	}

	return capnp.Client(c).SendStreamCall(ctx, s)

}

func (c ComputeStream) Execute(ctx context.Context, params func(ComputeStream_execute_Params) error) (ComputeStream_execute_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0xa891bd6fb18acabb,
			MethodID:      2,
			InterfaceName: "pkg/network/schema/caramba.capnp:ComputeStream",
			MethodName:    "execute",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 0}
		s.PlaceArgs = func(s capnp.Struct) error { return params(ComputeStream_execute_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return ComputeStream_execute_Results_Future{Future: ans.Future()}, release

}

func (c ComputeStream) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c ComputeStream) String() string {
	return "ComputeStream(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c ComputeStream) AddRef() ComputeStream {
	return ComputeStream(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c ComputeStream) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c ComputeStream) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c ComputeStream) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (ComputeStream) DecodeFromPtr(p capnp.Ptr) ComputeStream {
	return ComputeStream(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c ComputeStream) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c ComputeStream) IsSame(other ComputeStream) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c ComputeStream) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c ComputeStream) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A ComputeStream_Server is a ComputeStream with a local implementation.
type ComputeStream_Server interface {
	WriteNode(context.Context, ComputeStream_writeNode) error

	WriteTensor(context.Context, ComputeStream_writeTensor) error

	Execute(context.Context, ComputeStream_execute) error
}

// ComputeStream_NewServer creates a new Server from an implementation of ComputeStream_Server.
func ComputeStream_NewServer(s ComputeStream_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(ComputeStream_Methods(nil, s), s, c)
}

// ComputeStream_ServerToClient creates a new Client from an implementation of ComputeStream_Server.
// The caller is responsible for calling Release on the returned Client.
func ComputeStream_ServerToClient(s ComputeStream_Server) ComputeStream {
	return ComputeStream(capnp.NewClient(ComputeStream_NewServer(s)))
}

// ComputeStream_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func ComputeStream_Methods(methods []server.Method, s ComputeStream_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa891bd6fb18acabb,
			MethodID:      0,
			InterfaceName: "pkg/network/schema/caramba.capnp:ComputeStream",
			MethodName:    "writeNode",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.WriteNode(ctx, ComputeStream_writeNode{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa891bd6fb18acabb,
			MethodID:      1,
			InterfaceName: "pkg/network/schema/caramba.capnp:ComputeStream",
			MethodName:    "writeTensor",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.WriteTensor(ctx, ComputeStream_writeTensor{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0xa891bd6fb18acabb,
			MethodID:      2,
			InterfaceName: "pkg/network/schema/caramba.capnp:ComputeStream",
			MethodName:    "execute",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Execute(ctx, ComputeStream_execute{call})
		},
	})

	return methods
}

// ComputeStream_writeNode holds the state for a server call to ComputeStream.writeNode.
// See server.Call for documentation.
type ComputeStream_writeNode struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ComputeStream_writeNode) Args() ComputeStream_writeNode_Params {
	return ComputeStream_writeNode_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ComputeStream_writeNode) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// ComputeStream_writeTensor holds the state for a server call to ComputeStream.writeTensor.
// See server.Call for documentation.
type ComputeStream_writeTensor struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ComputeStream_writeTensor) Args() ComputeStream_writeTensor_Params {
	return ComputeStream_writeTensor_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ComputeStream_writeTensor) AllocResults() (stream.StreamResult, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return stream.StreamResult(r), err
}

// ComputeStream_execute holds the state for a server call to ComputeStream.execute.
// See server.Call for documentation.
type ComputeStream_execute struct {
	*server.Call
}

// Args returns the call's arguments.
func (c ComputeStream_execute) Args() ComputeStream_execute_Params {
	return ComputeStream_execute_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c ComputeStream_execute) AllocResults() (ComputeStream_execute_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ComputeStream_execute_Results(r), err
}

// ComputeStream_List is a list of ComputeStream.
type ComputeStream_List = capnp.CapList[ComputeStream]

// NewComputeStream_List creates a new list of ComputeStream.
func NewComputeStream_List(s *capnp.Segment, sz int32) (ComputeStream_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[ComputeStream](l), err
}

type ComputeStream_writeNode_Params capnp.Struct

// ComputeStream_writeNode_Params_TypeID is the unique identifier for the type ComputeStream_writeNode_Params.
const ComputeStream_writeNode_Params_TypeID = 0x83b73ad38ab110ff

func NewComputeStream_writeNode_Params(s *capnp.Segment) (ComputeStream_writeNode_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ComputeStream_writeNode_Params(st), err
}

func NewRootComputeStream_writeNode_Params(s *capnp.Segment) (ComputeStream_writeNode_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ComputeStream_writeNode_Params(st), err
}

func ReadRootComputeStream_writeNode_Params(msg *capnp.Message) (ComputeStream_writeNode_Params, error) {
	root, err := msg.Root()
	return ComputeStream_writeNode_Params(root.Struct()), err
}

func (s ComputeStream_writeNode_Params) String() string {
	str, _ := text.Marshal(0x83b73ad38ab110ff, capnp.Struct(s))
	return str
}

func (s ComputeStream_writeNode_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ComputeStream_writeNode_Params) DecodeFromPtr(p capnp.Ptr) ComputeStream_writeNode_Params {
	return ComputeStream_writeNode_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ComputeStream_writeNode_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ComputeStream_writeNode_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComputeStream_writeNode_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComputeStream_writeNode_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ComputeStream_writeNode_Params) Node() (IRNode, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return IRNode(p.Struct()), err
}

func (s ComputeStream_writeNode_Params) HasNode() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ComputeStream_writeNode_Params) SetNode(v IRNode) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewNode sets the node field to a newly
// allocated IRNode struct, preferring placement in s's segment.
func (s ComputeStream_writeNode_Params) NewNode() (IRNode, error) {
	ss, err := NewIRNode(capnp.Struct(s).Segment())
	if err != nil {
		return IRNode{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ComputeStream_writeNode_Params_List is a list of ComputeStream_writeNode_Params.
type ComputeStream_writeNode_Params_List = capnp.StructList[ComputeStream_writeNode_Params]

// NewComputeStream_writeNode_Params creates a new list of ComputeStream_writeNode_Params.
func NewComputeStream_writeNode_Params_List(s *capnp.Segment, sz int32) (ComputeStream_writeNode_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ComputeStream_writeNode_Params](l), err
}

// ComputeStream_writeNode_Params_Future is a wrapper for a ComputeStream_writeNode_Params promised by a client call.
type ComputeStream_writeNode_Params_Future struct{ *capnp.Future }

func (f ComputeStream_writeNode_Params_Future) Struct() (ComputeStream_writeNode_Params, error) {
	p, err := f.Future.Ptr()
	return ComputeStream_writeNode_Params(p.Struct()), err
}
func (p ComputeStream_writeNode_Params_Future) Node() IRNode_Future {
	return IRNode_Future{Future: p.Future.Field(0, nil)}
}

type ComputeStream_writeTensor_Params capnp.Struct

// ComputeStream_writeTensor_Params_TypeID is the unique identifier for the type ComputeStream_writeTensor_Params.
const ComputeStream_writeTensor_Params_TypeID = 0x8995aa6e9ed75b20

func NewComputeStream_writeTensor_Params(s *capnp.Segment) (ComputeStream_writeTensor_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ComputeStream_writeTensor_Params(st), err
}

func NewRootComputeStream_writeTensor_Params(s *capnp.Segment) (ComputeStream_writeTensor_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ComputeStream_writeTensor_Params(st), err
}

func ReadRootComputeStream_writeTensor_Params(msg *capnp.Message) (ComputeStream_writeTensor_Params, error) {
	root, err := msg.Root()
	return ComputeStream_writeTensor_Params(root.Struct()), err
}

func (s ComputeStream_writeTensor_Params) String() string {
	str, _ := text.Marshal(0x8995aa6e9ed75b20, capnp.Struct(s))
	return str
}

func (s ComputeStream_writeTensor_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ComputeStream_writeTensor_Params) DecodeFromPtr(p capnp.Ptr) ComputeStream_writeTensor_Params {
	return ComputeStream_writeTensor_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ComputeStream_writeTensor_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ComputeStream_writeTensor_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComputeStream_writeTensor_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComputeStream_writeTensor_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ComputeStream_writeTensor_Params) Tensor() (Tensor, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Tensor(p.Struct()), err
}

func (s ComputeStream_writeTensor_Params) HasTensor() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ComputeStream_writeTensor_Params) SetTensor(v Tensor) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewTensor sets the tensor field to a newly
// allocated Tensor struct, preferring placement in s's segment.
func (s ComputeStream_writeTensor_Params) NewTensor() (Tensor, error) {
	ss, err := NewTensor(capnp.Struct(s).Segment())
	if err != nil {
		return Tensor{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// ComputeStream_writeTensor_Params_List is a list of ComputeStream_writeTensor_Params.
type ComputeStream_writeTensor_Params_List = capnp.StructList[ComputeStream_writeTensor_Params]

// NewComputeStream_writeTensor_Params creates a new list of ComputeStream_writeTensor_Params.
func NewComputeStream_writeTensor_Params_List(s *capnp.Segment, sz int32) (ComputeStream_writeTensor_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ComputeStream_writeTensor_Params](l), err
}

// ComputeStream_writeTensor_Params_Future is a wrapper for a ComputeStream_writeTensor_Params promised by a client call.
type ComputeStream_writeTensor_Params_Future struct{ *capnp.Future }

func (f ComputeStream_writeTensor_Params_Future) Struct() (ComputeStream_writeTensor_Params, error) {
	p, err := f.Future.Ptr()
	return ComputeStream_writeTensor_Params(p.Struct()), err
}
func (p ComputeStream_writeTensor_Params_Future) Tensor() Tensor_Future {
	return Tensor_Future{Future: p.Future.Field(0, nil)}
}

type ComputeStream_execute_Params capnp.Struct

// ComputeStream_execute_Params_TypeID is the unique identifier for the type ComputeStream_execute_Params.
const ComputeStream_execute_Params_TypeID = 0xb3da532c810773b4

func NewComputeStream_execute_Params(s *capnp.Segment) (ComputeStream_execute_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ComputeStream_execute_Params(st), err
}

func NewRootComputeStream_execute_Params(s *capnp.Segment) (ComputeStream_execute_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0})
	return ComputeStream_execute_Params(st), err
}

func ReadRootComputeStream_execute_Params(msg *capnp.Message) (ComputeStream_execute_Params, error) {
	root, err := msg.Root()
	return ComputeStream_execute_Params(root.Struct()), err
}

func (s ComputeStream_execute_Params) String() string {
	str, _ := text.Marshal(0xb3da532c810773b4, capnp.Struct(s))
	return str
}

func (s ComputeStream_execute_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ComputeStream_execute_Params) DecodeFromPtr(p capnp.Ptr) ComputeStream_execute_Params {
	return ComputeStream_execute_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ComputeStream_execute_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ComputeStream_execute_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComputeStream_execute_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComputeStream_execute_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}

// ComputeStream_execute_Params_List is a list of ComputeStream_execute_Params.
type ComputeStream_execute_Params_List = capnp.StructList[ComputeStream_execute_Params]

// NewComputeStream_execute_Params creates a new list of ComputeStream_execute_Params.
func NewComputeStream_execute_Params_List(s *capnp.Segment, sz int32) (ComputeStream_execute_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 0}, sz)
	return capnp.StructList[ComputeStream_execute_Params](l), err
}

// ComputeStream_execute_Params_Future is a wrapper for a ComputeStream_execute_Params promised by a client call.
type ComputeStream_execute_Params_Future struct{ *capnp.Future }

func (f ComputeStream_execute_Params_Future) Struct() (ComputeStream_execute_Params, error) {
	p, err := f.Future.Ptr()
	return ComputeStream_execute_Params(p.Struct()), err
}

type ComputeStream_execute_Results capnp.Struct

// ComputeStream_execute_Results_TypeID is the unique identifier for the type ComputeStream_execute_Results.
const ComputeStream_execute_Results_TypeID = 0xa84e2ef50270cfd6

func NewComputeStream_execute_Results(s *capnp.Segment) (ComputeStream_execute_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ComputeStream_execute_Results(st), err
}

func NewRootComputeStream_execute_Results(s *capnp.Segment) (ComputeStream_execute_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4})
	return ComputeStream_execute_Results(st), err
}

func ReadRootComputeStream_execute_Results(msg *capnp.Message) (ComputeStream_execute_Results, error) {
	root, err := msg.Root()
	return ComputeStream_execute_Results(root.Struct()), err
}

func (s ComputeStream_execute_Results) String() string {
	str, _ := text.Marshal(0xa84e2ef50270cfd6, capnp.Struct(s))
	return str
}

func (s ComputeStream_execute_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ComputeStream_execute_Results) DecodeFromPtr(p capnp.Ptr) ComputeStream_execute_Results {
	return ComputeStream_execute_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ComputeStream_execute_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ComputeStream_execute_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ComputeStream_execute_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ComputeStream_execute_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ComputeStream_execute_Results) Outputs() (Tensor_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Tensor_List(p.List()), err
}

func (s ComputeStream_execute_Results) HasOutputs() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ComputeStream_execute_Results) SetOutputs(v Tensor_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewOutputs sets the outputs field to a newly
// allocated Tensor_List, preferring placement in s's segment.
func (s ComputeStream_execute_Results) NewOutputs(n int32) (Tensor_List, error) {
	l, err := NewTensor_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Tensor_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s ComputeStream_execute_Results) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ComputeStream_execute_Results) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ComputeStream_execute_Results) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ComputeStream_execute_Results) SetError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ComputeStream_execute_Results) WorkerAddress() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ComputeStream_execute_Results) HasWorkerAddress() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ComputeStream_execute_Results) WorkerAddressBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ComputeStream_execute_Results) SetWorkerAddress(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ComputeStream_execute_Results) WorkerSignature() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return []byte(p.Data()), err
}

func (s ComputeStream_execute_Results) HasWorkerSignature() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ComputeStream_execute_Results) SetWorkerSignature(v []byte) error {
	return capnp.Struct(s).SetData(3, v)
}

// ComputeStream_execute_Results_List is a list of ComputeStream_execute_Results.
type ComputeStream_execute_Results_List = capnp.StructList[ComputeStream_execute_Results]

// NewComputeStream_execute_Results creates a new list of ComputeStream_execute_Results.
func NewComputeStream_execute_Results_List(s *capnp.Segment, sz int32) (ComputeStream_execute_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 4}, sz)
	return capnp.StructList[ComputeStream_execute_Results](l), err
}

// ComputeStream_execute_Results_Future is a wrapper for a ComputeStream_execute_Results promised by a client call.
type ComputeStream_execute_Results_Future struct{ *capnp.Future }

func (f ComputeStream_execute_Results_Future) Struct() (ComputeStream_execute_Results, error) {
	p, err := f.Future.Ptr()
	return ComputeStream_execute_Results(p.Struct()), err
}

type Peer capnp.Client

// Peer_TypeID is the unique identifier for the type Peer.
const Peer_TypeID = 0x9d2958d03c86f978

func (c Peer) Ping(ctx context.Context, params func(Peer_ping_Params) error) (Peer_ping_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9d2958d03c86f978,
			MethodID:      0,
			InterfaceName: "pkg/network/schema/caramba.capnp:Peer",
			MethodName:    "ping",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Peer_ping_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Peer_ping_Results_Future{Future: ans.Future()}, release

}

func (c Peer) FindNode(ctx context.Context, params func(Peer_findNode_Params) error) (Peer_findNode_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9d2958d03c86f978,
			MethodID:      1,
			InterfaceName: "pkg/network/schema/caramba.capnp:Peer",
			MethodName:    "findNode",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 2}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Peer_findNode_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Peer_findNode_Results_Future{Future: ans.Future()}, release

}

func (c Peer) StartCompute(ctx context.Context, params func(Peer_startCompute_Params) error) (Peer_startCompute_Results_Future, capnp.ReleaseFunc) {

	s := capnp.Send{
		Method: capnp.Method{
			InterfaceID:   0x9d2958d03c86f978,
			MethodID:      2,
			InterfaceName: "pkg/network/schema/caramba.capnp:Peer",
			MethodName:    "startCompute",
		},
	}
	if params != nil {
		s.ArgsSize = capnp.ObjectSize{DataSize: 0, PointerCount: 1}
		s.PlaceArgs = func(s capnp.Struct) error { return params(Peer_startCompute_Params(s)) }
	}

	ans, release := capnp.Client(c).SendCall(ctx, s)
	return Peer_startCompute_Results_Future{Future: ans.Future()}, release

}

func (c Peer) WaitStreaming() error {
	return capnp.Client(c).WaitStreaming()
}

// String returns a string that identifies this capability for debugging
// purposes.  Its format should not be depended on: in particular, it
// should not be used to compare clients.  Use IsSame to compare clients
// for equality.
func (c Peer) String() string {
	return "Peer(" + capnp.Client(c).String() + ")"
}

// AddRef creates a new Client that refers to the same capability as c.
// If c is nil or has resolved to null, then AddRef returns nil.
func (c Peer) AddRef() Peer {
	return Peer(capnp.Client(c).AddRef())
}

// Release releases a capability reference.  If this is the last
// reference to the capability, then the underlying resources associated
// with the capability will be released.
//
// Release will panic if c has already been released, but not if c is
// nil or resolved to null.
func (c Peer) Release() {
	capnp.Client(c).Release()
}

// Resolve blocks until the capability is fully resolved or the Context
// expires.
func (c Peer) Resolve(ctx context.Context) error {
	return capnp.Client(c).Resolve(ctx)
}

func (c Peer) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Client(c).EncodeAsPtr(seg)
}

func (Peer) DecodeFromPtr(p capnp.Ptr) Peer {
	return Peer(capnp.Client{}.DecodeFromPtr(p))
}

// IsValid reports whether c is a valid reference to a capability.
// A reference is invalid if it is nil, has resolved to null, or has
// been released.
func (c Peer) IsValid() bool {
	return capnp.Client(c).IsValid()
}

// IsSame reports whether c and other refer to a capability created by the
// same call to NewClient.  This can return false negatives if c or other
// are not fully resolved: use Resolve if this is an issue.  If either
// c or other are released, then IsSame panics.
func (c Peer) IsSame(other Peer) bool {
	return capnp.Client(c).IsSame(capnp.Client(other))
}

// Update the flowcontrol.FlowLimiter used to manage flow control for
// this client. This affects all future calls, but not calls already
// waiting to send. Passing nil sets the value to flowcontrol.NopLimiter,
// which is also the default.
func (c Peer) SetFlowLimiter(lim fc.FlowLimiter) {
	capnp.Client(c).SetFlowLimiter(lim)
}

// Get the current flowcontrol.FlowLimiter used to manage flow control
// for this client.
func (c Peer) GetFlowLimiter() fc.FlowLimiter {
	return capnp.Client(c).GetFlowLimiter()
}

// A Peer_Server is a Peer with a local implementation.
type Peer_Server interface {
	Ping(context.Context, Peer_ping) error

	FindNode(context.Context, Peer_findNode) error

	StartCompute(context.Context, Peer_startCompute) error
}

// Peer_NewServer creates a new Server from an implementation of Peer_Server.
func Peer_NewServer(s Peer_Server) *server.Server {
	c, _ := s.(server.Shutdowner)
	return server.New(Peer_Methods(nil, s), s, c)
}

// Peer_ServerToClient creates a new Client from an implementation of Peer_Server.
// The caller is responsible for calling Release on the returned Client.
func Peer_ServerToClient(s Peer_Server) Peer {
	return Peer(capnp.NewClient(Peer_NewServer(s)))
}

// Peer_Methods appends Methods to a slice that invoke the methods on s.
// This can be used to create a more complicated Server.
func Peer_Methods(methods []server.Method, s Peer_Server) []server.Method {
	if cap(methods) == 0 {
		methods = make([]server.Method, 0, 3)
	}

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9d2958d03c86f978,
			MethodID:      0,
			InterfaceName: "pkg/network/schema/caramba.capnp:Peer",
			MethodName:    "ping",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.Ping(ctx, Peer_ping{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9d2958d03c86f978,
			MethodID:      1,
			InterfaceName: "pkg/network/schema/caramba.capnp:Peer",
			MethodName:    "findNode",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.FindNode(ctx, Peer_findNode{call})
		},
	})

	methods = append(methods, server.Method{
		Method: capnp.Method{
			InterfaceID:   0x9d2958d03c86f978,
			MethodID:      2,
			InterfaceName: "pkg/network/schema/caramba.capnp:Peer",
			MethodName:    "startCompute",
		},
		Impl: func(ctx context.Context, call *server.Call) error {
			return s.StartCompute(ctx, Peer_startCompute{call})
		},
	})

	return methods
}

// Peer_ping holds the state for a server call to Peer.ping.
// See server.Call for documentation.
type Peer_ping struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Peer_ping) Args() Peer_ping_Params {
	return Peer_ping_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Peer_ping) AllocResults() (Peer_ping_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_ping_Results(r), err
}

// Peer_findNode holds the state for a server call to Peer.findNode.
// See server.Call for documentation.
type Peer_findNode struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Peer_findNode) Args() Peer_findNode_Params {
	return Peer_findNode_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Peer_findNode) AllocResults() (Peer_findNode_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Peer_findNode_Results(r), err
}

// Peer_startCompute holds the state for a server call to Peer.startCompute.
// See server.Call for documentation.
type Peer_startCompute struct {
	*server.Call
}

// Args returns the call's arguments.
func (c Peer_startCompute) Args() Peer_startCompute_Params {
	return Peer_startCompute_Params(c.Call.Args())
}

// AllocResults allocates the results struct.
func (c Peer_startCompute) AllocResults() (Peer_startCompute_Results, error) {
	r, err := c.Call.AllocResults(capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_startCompute_Results(r), err
}

// Peer_List is a list of Peer.
type Peer_List = capnp.CapList[Peer]

// NewPeer_List creates a new list of Peer.
func NewPeer_List(s *capnp.Segment, sz int32) (Peer_List, error) {
	l, err := capnp.NewPointerList(s, sz)
	return capnp.CapList[Peer](l), err
}

type Peer_ping_Params capnp.Struct

// Peer_ping_Params_TypeID is the unique identifier for the type Peer_ping_Params.
const Peer_ping_Params_TypeID = 0xe98daa68a52378ea

func NewPeer_ping_Params(s *capnp.Segment) (Peer_ping_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_ping_Params(st), err
}

func NewRootPeer_ping_Params(s *capnp.Segment) (Peer_ping_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_ping_Params(st), err
}

func ReadRootPeer_ping_Params(msg *capnp.Message) (Peer_ping_Params, error) {
	root, err := msg.Root()
	return Peer_ping_Params(root.Struct()), err
}

func (s Peer_ping_Params) String() string {
	str, _ := text.Marshal(0xe98daa68a52378ea, capnp.Struct(s))
	return str
}

func (s Peer_ping_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Peer_ping_Params) DecodeFromPtr(p capnp.Ptr) Peer_ping_Params {
	return Peer_ping_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Peer_ping_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Peer_ping_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Peer_ping_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Peer_ping_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Peer_ping_Params) Sender() (NodeInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return NodeInfo(p.Struct()), err
}

func (s Peer_ping_Params) HasSender() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Peer_ping_Params) SetSender(v NodeInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewSender sets the sender field to a newly
// allocated NodeInfo struct, preferring placement in s's segment.
func (s Peer_ping_Params) NewSender() (NodeInfo, error) {
	ss, err := NewNodeInfo(capnp.Struct(s).Segment())
	if err != nil {
		return NodeInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Peer_ping_Params_List is a list of Peer_ping_Params.
type Peer_ping_Params_List = capnp.StructList[Peer_ping_Params]

// NewPeer_ping_Params creates a new list of Peer_ping_Params.
func NewPeer_ping_Params_List(s *capnp.Segment, sz int32) (Peer_ping_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Peer_ping_Params](l), err
}

// Peer_ping_Params_Future is a wrapper for a Peer_ping_Params promised by a client call.
type Peer_ping_Params_Future struct{ *capnp.Future }

func (f Peer_ping_Params_Future) Struct() (Peer_ping_Params, error) {
	p, err := f.Future.Ptr()
	return Peer_ping_Params(p.Struct()), err
}
func (p Peer_ping_Params_Future) Sender() NodeInfo_Future {
	return NodeInfo_Future{Future: p.Future.Field(0, nil)}
}

type Peer_ping_Results capnp.Struct

// Peer_ping_Results_TypeID is the unique identifier for the type Peer_ping_Results.
const Peer_ping_Results_TypeID = 0xbbd55256275b07e6

func NewPeer_ping_Results(s *capnp.Segment) (Peer_ping_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_ping_Results(st), err
}

func NewRootPeer_ping_Results(s *capnp.Segment) (Peer_ping_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_ping_Results(st), err
}

func ReadRootPeer_ping_Results(msg *capnp.Message) (Peer_ping_Results, error) {
	root, err := msg.Root()
	return Peer_ping_Results(root.Struct()), err
}

func (s Peer_ping_Results) String() string {
	str, _ := text.Marshal(0xbbd55256275b07e6, capnp.Struct(s))
	return str
}

func (s Peer_ping_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Peer_ping_Results) DecodeFromPtr(p capnp.Ptr) Peer_ping_Results {
	return Peer_ping_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Peer_ping_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Peer_ping_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Peer_ping_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Peer_ping_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Peer_ping_Results) Responder() (NodeInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return NodeInfo(p.Struct()), err
}

func (s Peer_ping_Results) HasResponder() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Peer_ping_Results) SetResponder(v NodeInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResponder sets the responder field to a newly
// allocated NodeInfo struct, preferring placement in s's segment.
func (s Peer_ping_Results) NewResponder() (NodeInfo, error) {
	ss, err := NewNodeInfo(capnp.Struct(s).Segment())
	if err != nil {
		return NodeInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Peer_ping_Results_List is a list of Peer_ping_Results.
type Peer_ping_Results_List = capnp.StructList[Peer_ping_Results]

// NewPeer_ping_Results creates a new list of Peer_ping_Results.
func NewPeer_ping_Results_List(s *capnp.Segment, sz int32) (Peer_ping_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Peer_ping_Results](l), err
}

// Peer_ping_Results_Future is a wrapper for a Peer_ping_Results promised by a client call.
type Peer_ping_Results_Future struct{ *capnp.Future }

func (f Peer_ping_Results_Future) Struct() (Peer_ping_Results, error) {
	p, err := f.Future.Ptr()
	return Peer_ping_Results(p.Struct()), err
}
func (p Peer_ping_Results_Future) Responder() NodeInfo_Future {
	return NodeInfo_Future{Future: p.Future.Field(0, nil)}
}

type Peer_findNode_Params capnp.Struct

// Peer_findNode_Params_TypeID is the unique identifier for the type Peer_findNode_Params.
const Peer_findNode_Params_TypeID = 0x9eccaa3e48d80a3b

func NewPeer_findNode_Params(s *capnp.Segment) (Peer_findNode_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Peer_findNode_Params(st), err
}

func NewRootPeer_findNode_Params(s *capnp.Segment) (Peer_findNode_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Peer_findNode_Params(st), err
}

func ReadRootPeer_findNode_Params(msg *capnp.Message) (Peer_findNode_Params, error) {
	root, err := msg.Root()
	return Peer_findNode_Params(root.Struct()), err
}

func (s Peer_findNode_Params) String() string {
	str, _ := text.Marshal(0x9eccaa3e48d80a3b, capnp.Struct(s))
	return str
}

func (s Peer_findNode_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Peer_findNode_Params) DecodeFromPtr(p capnp.Ptr) Peer_findNode_Params {
	return Peer_findNode_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Peer_findNode_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Peer_findNode_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Peer_findNode_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Peer_findNode_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Peer_findNode_Params) Sender() (NodeInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return NodeInfo(p.Struct()), err
}

func (s Peer_findNode_Params) HasSender() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Peer_findNode_Params) SetSender(v NodeInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewSender sets the sender field to a newly
// allocated NodeInfo struct, preferring placement in s's segment.
func (s Peer_findNode_Params) NewSender() (NodeInfo, error) {
	ss, err := NewNodeInfo(capnp.Struct(s).Segment())
	if err != nil {
		return NodeInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Peer_findNode_Params) TargetId() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return []byte(p.Data()), err
}

func (s Peer_findNode_Params) HasTargetId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Peer_findNode_Params) SetTargetId(v []byte) error {
	return capnp.Struct(s).SetData(1, v)
}

// Peer_findNode_Params_List is a list of Peer_findNode_Params.
type Peer_findNode_Params_List = capnp.StructList[Peer_findNode_Params]

// NewPeer_findNode_Params creates a new list of Peer_findNode_Params.
func NewPeer_findNode_Params_List(s *capnp.Segment, sz int32) (Peer_findNode_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Peer_findNode_Params](l), err
}

// Peer_findNode_Params_Future is a wrapper for a Peer_findNode_Params promised by a client call.
type Peer_findNode_Params_Future struct{ *capnp.Future }

func (f Peer_findNode_Params_Future) Struct() (Peer_findNode_Params, error) {
	p, err := f.Future.Ptr()
	return Peer_findNode_Params(p.Struct()), err
}
func (p Peer_findNode_Params_Future) Sender() NodeInfo_Future {
	return NodeInfo_Future{Future: p.Future.Field(0, nil)}
}

type Peer_findNode_Results capnp.Struct

// Peer_findNode_Results_TypeID is the unique identifier for the type Peer_findNode_Results.
const Peer_findNode_Results_TypeID = 0xcb9ca74809b046f6

func NewPeer_findNode_Results(s *capnp.Segment) (Peer_findNode_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Peer_findNode_Results(st), err
}

func NewRootPeer_findNode_Results(s *capnp.Segment) (Peer_findNode_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return Peer_findNode_Results(st), err
}

func ReadRootPeer_findNode_Results(msg *capnp.Message) (Peer_findNode_Results, error) {
	root, err := msg.Root()
	return Peer_findNode_Results(root.Struct()), err
}

func (s Peer_findNode_Results) String() string {
	str, _ := text.Marshal(0xcb9ca74809b046f6, capnp.Struct(s))
	return str
}

func (s Peer_findNode_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Peer_findNode_Results) DecodeFromPtr(p capnp.Ptr) Peer_findNode_Results {
	return Peer_findNode_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Peer_findNode_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Peer_findNode_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Peer_findNode_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Peer_findNode_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Peer_findNode_Results) Responder() (NodeInfo, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return NodeInfo(p.Struct()), err
}

func (s Peer_findNode_Results) HasResponder() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Peer_findNode_Results) SetResponder(v NodeInfo) error {
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewResponder sets the responder field to a newly
// allocated NodeInfo struct, preferring placement in s's segment.
func (s Peer_findNode_Results) NewResponder() (NodeInfo, error) {
	ss, err := NewNodeInfo(capnp.Struct(s).Segment())
	if err != nil {
		return NodeInfo{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Peer_findNode_Results) Nodes() (NodeInfo_List, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return NodeInfo_List(p.List()), err
}

func (s Peer_findNode_Results) HasNodes() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Peer_findNode_Results) SetNodes(v NodeInfo_List) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewNodes sets the nodes field to a newly
// allocated NodeInfo_List, preferring placement in s's segment.
func (s Peer_findNode_Results) NewNodes(n int32) (NodeInfo_List, error) {
	l, err := NewNodeInfo_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return NodeInfo_List{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}

// Peer_findNode_Results_List is a list of Peer_findNode_Results.
type Peer_findNode_Results_List = capnp.StructList[Peer_findNode_Results]

// NewPeer_findNode_Results creates a new list of Peer_findNode_Results.
func NewPeer_findNode_Results_List(s *capnp.Segment, sz int32) (Peer_findNode_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[Peer_findNode_Results](l), err
}

// Peer_findNode_Results_Future is a wrapper for a Peer_findNode_Results promised by a client call.
type Peer_findNode_Results_Future struct{ *capnp.Future }

func (f Peer_findNode_Results_Future) Struct() (Peer_findNode_Results, error) {
	p, err := f.Future.Ptr()
	return Peer_findNode_Results(p.Struct()), err
}
func (p Peer_findNode_Results_Future) Responder() NodeInfo_Future {
	return NodeInfo_Future{Future: p.Future.Field(0, nil)}
}

type Peer_startCompute_Params capnp.Struct

// Peer_startCompute_Params_TypeID is the unique identifier for the type Peer_startCompute_Params.
const Peer_startCompute_Params_TypeID = 0xdf877a4f6f207c1d

func NewPeer_startCompute_Params(s *capnp.Segment) (Peer_startCompute_Params, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_startCompute_Params(st), err
}

func NewRootPeer_startCompute_Params(s *capnp.Segment) (Peer_startCompute_Params, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_startCompute_Params(st), err
}

func ReadRootPeer_startCompute_Params(msg *capnp.Message) (Peer_startCompute_Params, error) {
	root, err := msg.Root()
	return Peer_startCompute_Params(root.Struct()), err
}

func (s Peer_startCompute_Params) String() string {
	str, _ := text.Marshal(0xdf877a4f6f207c1d, capnp.Struct(s))
	return str
}

func (s Peer_startCompute_Params) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Peer_startCompute_Params) DecodeFromPtr(p capnp.Ptr) Peer_startCompute_Params {
	return Peer_startCompute_Params(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Peer_startCompute_Params) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Peer_startCompute_Params) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Peer_startCompute_Params) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Peer_startCompute_Params) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Peer_startCompute_Params) GraphId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Peer_startCompute_Params) HasGraphId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Peer_startCompute_Params) GraphIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Peer_startCompute_Params) SetGraphId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// Peer_startCompute_Params_List is a list of Peer_startCompute_Params.
type Peer_startCompute_Params_List = capnp.StructList[Peer_startCompute_Params]

// NewPeer_startCompute_Params creates a new list of Peer_startCompute_Params.
func NewPeer_startCompute_Params_List(s *capnp.Segment, sz int32) (Peer_startCompute_Params_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Peer_startCompute_Params](l), err
}

// Peer_startCompute_Params_Future is a wrapper for a Peer_startCompute_Params promised by a client call.
type Peer_startCompute_Params_Future struct{ *capnp.Future }

func (f Peer_startCompute_Params_Future) Struct() (Peer_startCompute_Params, error) {
	p, err := f.Future.Ptr()
	return Peer_startCompute_Params(p.Struct()), err
}

type Peer_startCompute_Results capnp.Struct

// Peer_startCompute_Results_TypeID is the unique identifier for the type Peer_startCompute_Results.
const Peer_startCompute_Results_TypeID = 0xb8af66c3089cf7aa

func NewPeer_startCompute_Results(s *capnp.Segment) (Peer_startCompute_Results, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_startCompute_Results(st), err
}

func NewRootPeer_startCompute_Results(s *capnp.Segment) (Peer_startCompute_Results, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return Peer_startCompute_Results(st), err
}

func ReadRootPeer_startCompute_Results(msg *capnp.Message) (Peer_startCompute_Results, error) {
	root, err := msg.Root()
	return Peer_startCompute_Results(root.Struct()), err
}

func (s Peer_startCompute_Results) String() string {
	str, _ := text.Marshal(0xb8af66c3089cf7aa, capnp.Struct(s))
	return str
}

func (s Peer_startCompute_Results) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Peer_startCompute_Results) DecodeFromPtr(p capnp.Ptr) Peer_startCompute_Results {
	return Peer_startCompute_Results(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Peer_startCompute_Results) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Peer_startCompute_Results) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Peer_startCompute_Results) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Peer_startCompute_Results) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Peer_startCompute_Results) Stream() ComputeStream {
	p, _ := capnp.Struct(s).Ptr(0)
	return ComputeStream(p.Interface().Client())
}

func (s Peer_startCompute_Results) HasStream() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Peer_startCompute_Results) SetStream(v ComputeStream) error {
	if !v.IsValid() {
		return capnp.Struct(s).SetPtr(0, capnp.Ptr{})
	}
	seg := s.Segment()
	in := capnp.NewInterface(seg, seg.Message().CapTable().Add(capnp.Client(v)))
	return capnp.Struct(s).SetPtr(0, in.ToPtr())
}

// Peer_startCompute_Results_List is a list of Peer_startCompute_Results.
type Peer_startCompute_Results_List = capnp.StructList[Peer_startCompute_Results]

// NewPeer_startCompute_Results creates a new list of Peer_startCompute_Results.
func NewPeer_startCompute_Results_List(s *capnp.Segment, sz int32) (Peer_startCompute_Results_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[Peer_startCompute_Results](l), err
}

// Peer_startCompute_Results_Future is a wrapper for a Peer_startCompute_Results promised by a client call.
type Peer_startCompute_Results_Future struct{ *capnp.Future }

func (f Peer_startCompute_Results_Future) Struct() (Peer_startCompute_Results, error) {
	p, err := f.Future.Ptr()
	return Peer_startCompute_Results(p.Struct()), err
}
func (p Peer_startCompute_Results_Future) Stream() ComputeStream {
	return ComputeStream(p.Future.Field(0, nil).Client())
}

const schema_89808d3353fbc573 = "x\xda\x9cVkl\x14e\x17>\xe7}w\xbb\xbb\xa5" +
	"\xb7\xf9\xb6_\xf2\xe5\xcbG\x16\xf2\x15\x15\x82-\xb4\x98" +
	"H\x11\xbb\x16\xd1.\x11\xdcw\x0b\x04\xc4D\xa6;\xef" +
	"\xb6+\xed\xcc03K\x0b)) \xa8\x10H\xbc\x84" +
	"D\x09\xf2G\x89\xa5\x89\xc1*\xc6\x0b\x9ah\x88A\xd4" +
	"D\xa3\xf1\x02\x7f\x8c\x7f4\x98\x18\x03\x89\x124f\xcc" +
	"\x99\xdd\xd9\x1dzI\x0b\xff&\xa7O\xcf\xe59\xcfy" +
	"\xde]\xf2\x0aO\x86\x96\xd6>\x18\x05&\xb6\x86\xab\\" +
	"\xb7a\xfc\xd0\xd7\xedo?\x01J\x0b\x02\x841\x02\xd0" +
	"\x16\x0b1\x06\x18\x9f\x1b\xea\x00t\xe7m\xf9\xee\x84>" +
	"v\xf4`\x10\xb02\xf4/\x02l\xf0\x00+6mw" +
	"\xaf\xfdz\xecyP\xe6\xa3k\x7f\xfcWw\xdb\x91=" +
	"\x07!\x1c\"`!\xd4\x89\xf1\x03\xf4\x19\xdf\x1b\xfa\x19" +
	"\xd0\x1d\xba\xfe\xe4=_nZ\xf8\x12(\xf3y\x05\x0c" +
	"\xd8&\xc3\xad\x18/\x84\x09\xb9=|>~\x85\xbe\xdc" +
	"\x15\xd5\xdfw\xdd;\xf6\xf9\x09Pn\xa3\xda\x8cR^" +
	"\x0c\xbf\x81\x80\xf1\xcb\xe1A@wY\xee\xea'\x1b\xdf" +
	"o\x1f\x9d\xaav\xaa\xaa\x13\xe3\x9b\xab(\xe3\x86*\xaa" +
	"\xfd\xed\x17&\xfb\xbdy\xddhi\x12\x0f\xb4<\xf2'" +
	"e[\x1b!\xc0\xd9O\x0f\x8d\x1b\x1f<;:\xa9\xb9" +
	"\xe5\xd1]\x18_\x1b\xa5T\xa9\xe8\xf9\xf8\x05\xfar\xcf" +
	"\xd8\x91\xbd\x8b\xbb/\xbdYL\xe7e\x1b\x8f^E\x08" +
	"\xb9/\x9f\xcd\x8e\x9e\xda\x9c8\x03b>\x06\x12\x15\xb9" +
	";\x19\xdd\x87\xf1w\xbd\\oE\xa9\xea\xd8\xb5\xe3\xd1" +
	"s\xb9\xd3\xef\x94\x86\xf4@\xaf\xc5.Q[\x1f\xc5\x88" +
	"\xe0\x9f\"[n\xdf\x98\xf9\xe6l\x10\xf0c\xec\x18\x01" +
	"\xaex\x80?\x1ex=\xd6\xf5\xea\xf1\xcf\x824\xfd\xbb" +
	"\xfa=\x02,\xa8&\x9a\xe6\x0e\xcf3\x1e\xde\xf5\xd4\x0f" +
	"\xc1\x0cG\xab\xbf\"\xc0\xa9j\xca\xf0\xcb\xd0\xffO\xf6" +
	"\x8d\x1d\xb9\x1c\x04\\\xa8~\x8e\x00\x17=@O\xfb\xb9" +
	"\xe1\xbe\xbf\xff\xf7\xdb\x04\xa29\x01\xafWg0^;" +
	"\x87&\x8a\xcd9\x0d\x9b]s[o\x8b.\x9d\xc1\x88" +
	"amk\xb1\xb3}r@m\xc9\xaa\x96:\xd0\xa36" +
	"gUS7\xdbW\x19\x03f\xc1\x91\xdd\x8e%\xd5\x81" +
	"\xe6A+\xef\xc8u\x86&\x9b\xd2\x84\xb2A\x84x\x08" +
	" \x84\x00J\xed\"\x00\x11\xe5(\x1a\x19\xd6\xeb\x86&" +
	"\xb1\xa1\xa28@l\x00\xbc\xb5z\xeb\xa5n\x1bV\xb1" +
	"\"\xda\xc1\x8a\xed\x95\x8a\x1d\x8e\x87\xc2\x86\x8a\xd2&\xd4" +
	"\x0cM[3\x95\xa1\x91 \x8d(\x1a\xca\xc9\xd5\xff\x02" +
	"\x88G9\x8a>\x86\x0ab#RPRp+G\xd1" +
	"\xcfPa\xac\x11\x19\x80\x92\xa764\x8eb\x0fC\x85" +
	"\xf3F\xe4\x00\xcan\x0a\x0eq\x14\xfb\x19\xf2\xbc\x865" +
	"\xc0\xb0\x06\x90\x1b\xa6\xff\xd9\x91\xd7\xcd\x82cc\x1d`" +
	"\x9a\xa3\x17\xad\x03\xec\xc8\x1az.\xdf\x8b\xb5\xc0\xb06" +
	"\xd0=\x9f\xae\xfbD{ZJ\x8bz\xaf\xe1a\x80\xb2" +
	"@\xd0\x17\xa3\"\x16\x01SVG\x10\xcbW\x8a\xbe\x0e" +
	"\x95\xe5k\x80)K#\xc8\xca\xcaC_\xe5\xca\x82\xc7" +
	"\x81)s#\xf5f^\xefM\xa2\x9b\xcb\xeb\x9a\xc7\x13" +
	"@\x12]\xdbQ-g\x951\x00\xf5\xb4\xae$\xa6\xb1" +
	"\xd2kxZ\xa6\xa9\xd5f?QS:\xe1\x89HD" +
	"\xcb\xa4/$\xd6\x9a8\x8a%\x01\xd2\xef\\\x03 \x16" +
	"s\x14w3\xec\xb0\xa5\xaeIZsY\xe7\xa55;" +
	"\xaa\xd5+\x9d\x94\x06\x00\x93\xc8\x9b~\xf5Em\xcdj" +
	"\xf5\xad\xa5\xd5\x0f\x07V\xbf\x934\xefL\\}\xeb\x94" +
	"\xabO\xd8}\xaa)\xfdu\x87\x8b\xeb\xae\xd7TG\xf5" +
	"\xfbMh\xceNS\xfa\xf8r\xf7U\xb3<\x169$" +
	"\xb3\x05G6e:\xa4]\xe8w\xec\xe0D\x9d\xa5\x89" +
	"\x86\x02\x13\x15\xa8Os\xe2DV\xa5\xf9\xf2D{\xf7" +
	"\x01\x88=\x1c\xc5a\x86#F\xc1\x09\xea\xf6\xc6\x83\xab" +
	"\x03LH\xcb2\xac\xf2\x14\x83\x86\xb5MZ\xf7i\x90" +
	"\xd0,i\xdb\x13\xe2\xddy\xec\xd5U\xa7`\xc9\x9b\xd9" +
	"Zi\xee\x8e\xe2\xe0\x15\xed\xfbO$\xea\xe3\x1f\x0e\xb6" +
	"\x1d{\xecEEd\x80))\xd2\xbe\xff:V\xfe\xb6" +
	"\xb2\x07\x98r\x17i\xdf\x7f \xd0\x7fx\x94\x85\x9d\x9e" +
	"\xf6]\xdf\xf0\x00e\x12]\xdf\x8e b\x1bV\x12G" +
	"J\x8c\xdf\xa8\xfe\x9b]W\xe9\x0afq=\xa5\xffO" +
	"[F.\xdf?\xc9\xaf\x0eU\\\xc8\xdf\xf0\xee\x0c\x80" +
	"\x18\xe6(\x9e\xa6\x0dcq\xc3\x07\xe8\x9c\xf6s\x14\xcf" +
	"\xd0\x86Yq\xc3G\x1e\x01\x10\x879\x8a\x17\x18\xba\xea" +
	"\x0e5\xdf\xaf\xf6\xf4\xa3\xcc\x14t]Z6\xc0\x04\x97" +
	"rwX\xea@\xe7NG\x02\xda\x18\x03\x861@\xb7" +
	"\x14\xb2\xe9\x02\xfdX\xae\xdf0\xd3\xd2\xea\x06.\xb3\xe5" +
	"\xe0\xccLy>\xe1[\x8c\xe9\x89\x9a4\xcd\x9di\xed" +
	"\xdf\xf6HE\xa5\xf2\xd3\x00\x10\x15\x98\xb5)\x91\xc9M" +
	"Y\x84(\xac\xe1(\xfe\xc3\xd0\xb5\xa4m\x1a\xba&\x01" +
	"\xa7r\xa0\x9b\xb5\xbf\xf2\x9d\x06\xfc\x8f\xaa\xdd\xc1Q," +
	"\x0b\xdc\xe9\xd2\xd6\x92\xffu\xcd\xd4B\x82\x9e\xdd\xc0e" +
	"\x06\xff\\w\x8b\xc4O\xf1\xecvVx\x1f\xe9\xb5T" +
	"\xb3/\xa5M2\xad\xd9\xd0=\xc3\x8b>\xad\xd5\xcfl" +
	"\x10\xc4oJ\xcf\xa1Q\xf4\x06?\xfdj2\xf6$G" +
	"\xf1P\x80\xde\x14\x8ds?G\x91\x0e\xd8\xe0Z\x0av" +
	"q\x14\xeb\x8b\x1e^\xf2\xa6\x11U\xbb\xc1\xc5F\xcc\xe2" +
	"-bC\xe5\xa7d\xb1\xc9\x7f\x02\x00\x00\xff\xff\xf8\xce" +
	"(\xaa"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_89808d3353fbc573,
		Nodes: []uint64{
			0x83b73ad38ab110ff,
			0x8995aa6e9ed75b20,
			0x939aedf7ff71583b,
			0x9d2958d03c86f978,
			0x9eccaa3e48d80a3b,
			0xa83abc56c8f26634,
			0xa84e2ef50270cfd6,
			0xa891bd6fb18acabb,
			0xb3da532c810773b4,
			0xb41f59a9a863bba3,
			0xb8af66c3089cf7aa,
			0xbbd55256275b07e6,
			0xcb9ca74809b046f6,
			0xdf877a4f6f207c1d,
			0xe98daa68a52378ea,
			0xef1cfd687cc33a62,
		},
		Compressed: true,
	})
}
